version: "3.1"

services:
    rabbitmq:
        build:
            context: docker
            dockerfile: rabbitmq-Dockerfile
        ports:
            - 4369:4369
            - 5671:5671
            - 5672:5672
            - 25672:25672