server:
  port: ${PORT:2002}

spring:
  application:
    name: ant-network-rest
  freemarker:
      enabled: false

  data:
    mongodb:
      host: server.threeq.me
      port: 27017
      database: ant-network

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2001/eureka/
