server:
  port: ${PORT:2002}

spring:
  application:
    name: ant-network-server-turbine

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    wait-time-in-ms-when-sync-empty: 0

