server:
  port: ${PORT:2003}

spring:
  application:
    name: ant-network-rest1
  freemarker:
      enabled: false

  data:
    mongodb:
      host: server.threeq.me
      port: 27017
      database: ant-rest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2001/eureka/
